// src/constants.ts

export const INTERESTS = [
  'Reading',
  'Writing',
  'Movies',
  'Music',
  'Traveling',
  'Hiking',
  'Cooking',
  'Gaming',
  'Photography',
  'Art',
  'Sports',
  'Technology',
  'History',
  'Science',
  'Gardening',
  'Dancing',
  'Yoga',
  'Meditation',
  'Volunteering',
  'Learning Languages',
  'DIY Crafts',
  'Fashion',
  'Fitness',
  'Running',
  'Cycling',
  'Swimming',
  'Camping',
  'Fishing',
  'Board Games',
  'Puzzles',
  'Calligraphy',
  'Painting',
  'Drawing',
  'Sculpting',
  'Blogging',
  'Vlogging',
  'Podcasting',
  'Astronomy',
  'Bird Watching',
  'Collecting',
  'Antiques',
  'Stamps',
  'Coins',
  'Vinyl Records',
  'Comic Books',
  'Action Figures',
  'Cars',
  'Motorcycles',
  'Woodworking',
  'Knitting',
  'Sewing',
  'Embroidery',
  'Baking',
  'Wine Tasting',
  'Beer Brewing',
  'Coffee Connoisseur',
  'Tea Enthusiast',
  'Martial Arts',
  'Archery',
  'Rock Climbing',
  'Skiing',
  'Snowboarding',
  'Surfing',
  'Sailing',
  'Kayaking',
  'Canoeing',
  'Stand-up Paddleboarding',
  'Scuba Diving',
  'Snorkeling',
  'Skateboarding',
  'Rollerblading',
  'Ice Skating',
  'Fencing',
  'Theater',
  'Acting',
  'Stand-up Comedy',
  'Improv',
  'Magic',
  'Juggling',
  'Playing an Instrument',
  'Guitar',
  'Piano',
  'Violin',
  'Drums',
  'Singing',
  'Songwriting',
  'Music Production',
  'DJing',
  'Philosophy',
  'Psychology',
  'Sociology',
  'Politics',
  'Economics',
  'Architecture',
  'Interior Design',
  'Urban Exploration',
  'Geocaching',
  'Thrifting',
  'Minimalism',
  'Sustainability',
];

export const LANGUAGES = [
  'English',
  'Spanish',
  'French',
  'German',
  'Mandarin Chinese',
  'Hindi',
  'Arabic',
  'Portuguese',
  'Russian',
  'Japanese',
  'Bengali',
  'Punjabi',
  'Javanese',
  'Wu Chinese',
  'Telugu',
  'Marathi',
  'Turkish',
  'Korean',
  'Vietnamese',
  'Tamil',
  'Urdu',
  'Italian',
  'Yue Chinese',
  'Persian',
  'Gujarati',
  'Bhojpuri',
  'Min Nan Chinese',
  'Hakka Chinese',
  'Kannada',
  'Indonesian',
  'Malayalam',
  'Odia',
  'Burmese',
  'Polish',
  'Ukrainian',
  'Maithili',
  'Sunda',
  'Fula',
  'Romanian',
  'Dutch',
  'Uzbek',
  'Yoruba',
  'Amharic',
  'Igbo',
  'Oromo',
  'Tagalog',
  'Thai',
  'Saraiki',
  'Lao',
  'Khmer',
  'Swahili',
  'Greek',
  'Hebrew',
  'Swedish',
  'Danish',
  'Norwegian',
  'Finnish',
  'Hungarian',
  'Czech',
  'Slovak',
];
